name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
# 指定此工作流程的触发器
on: [push]
jobs:
  # 定义名称为"check-bats-version"的job
  image-build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: /usr/local/bin/ansible la -i /home/runner/hosts -m shell -a "cd /home/runner/actions-runner/_work/github_ci_learn/github_ci_learn/ && make build"
